# Generated by Django 5.2.5 on 2025-09-03 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'permissions': [('change_status', 'Can change the status of tasks')]},
        ),
    ]
