# Generated by Django 5.2.5 on 2025-08-25 10:48

from django.db import migrations


def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    participants_group, participants_created = Group.objects.get_or_create(name='Participants')
    moderators_group, moderators_created = Group.objects.get_or_create(name='Moderators')
    #TODO: assign permissions to these groups once necessary models are created


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial')
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
