# Generated by Django 5.2.5 on 2025-08-25 10:48
from django.db import migrations
from users.utils import permission_codenames

def create_groups(apps, schema_editor):

    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    Photo = apps.get_model('coreapp', 'Photo')
    Vote = apps.get_model('coreapp', 'Vote')
    Comment = apps.get_model('coreapp', 'Comment')

    participants_group, _ = Group.objects.get_or_create(name='Participants')
    moderators_group, _ = Group.objects.get_or_create(name='Moderators')

    photo_ct = ContentType.objects.get_for_model(Photo)
    vote_ct = ContentType.objects.get_for_model(Vote)
    comment_ct = ContentType.objects.get_for_model(Comment)

    participants_permissions = Permission.objects.filter(content_type__in=[photo_ct,vote_ct,comment_ct],
                                                         codename__in=permission_codenames['participants'])


    moderators_permissions = Permission.objects.filter(content_type__in=[photo_ct,vote_ct,comment_ct],
                                                         codename__in=permission_codenames['moderators'])

    participants_group.permissions.add(*participants_permissions)
    moderators_group.permissions.add(*moderators_permissions)
    
class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial')
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
