"""
Django settings for photocontest project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATIC_URL = "static/"

MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-qk#%f82#tu=1z6^(nh*7)07qp*&q=%4hsp7aashik*84d=^@fa'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'models_app',
    'users_api',
    'contest_api',
    'rest_framework',
    'rest_framework.authtoken',
    'imagekit',
    'service_objects',
    'drf_spectacular'
]

MIDDLEWARE = [
    "log_request_id.middleware.RequestIDMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'conf.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'conf.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'photocontest',
        'USER': 'postgres',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'models_app.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],

    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',

    'EXCEPTION_HANDLER': 'utils.exception_handler.drf_exception_response',

    'PAGE_SIZE': 4,


}

CELERY_BROKER_URL = "redis://localhost:6379/0"


SWAGGER_SETTINGS = {
    "DOC_EXPANSION": "list",
    "SHOW_EXTENSIONS": True,
    "USE_SESSION_AUTH": False,
    "TAGS_SORTER": "alpha",
    "OPERATIONS_SORTER": "method",
    "DEFAULT_MODEL_RENDERING": "example",
    "SECURITY_DEFINITIONS": {},
}


SPECTACULAR_SETTINGS = {
    "TITLE": "REST API",
    "DESCRIPTION": "API endpoints",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "SWAGGER_UI_SETTINGS": {
        "displayOperationId": False,
        "displayRequestDuration": True,
    },
}
from conf.settings.celery import CELERY_LOG_LEVEL
from conf.settings.django import BASE_DIR, env

LOG_LEVEL = env.str("LOG_LEVEL", default="INFO")

DEBUG_LOGGING = env.bool("DEBUG_LOGGING", default=False)

if DEBUG_LOGGING:
    ERROR_LOG_FILE_PATH = env.str(
        "ERROR_LOG_FILE_PATH",
        default=os.path.join(BASE_DIR, "logs", "error.log"),
    )
    CELERY_LOG_PATH = os.path.join(
        BASE_DIR, env.str("CELERY_LOG_PATH", default="logs/celery.log")
    )
    if not os.path.exists(os.path.join(BASE_DIR, "logs")):
        Path(os.path.join(BASE_DIR, "logs")).mkdir(parents=True, exist_ok=True)

    if not os.path.exists(ERROR_LOG_FILE_PATH):
        Path(os.path.join(BASE_DIR, ERROR_LOG_FILE_PATH)).touch(exist_ok=True)

    if not os.path.exists(CELERY_LOG_PATH):
        Path(os.path.join(BASE_DIR, CELERY_LOG_PATH)).touch(exist_ok=True)

    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "formatters": {
            "standard": {
                "format": "%(levelname)-8s [%(asctime)s] %(levelname)s [%(request_id)s]: %(message)s"
            },
            "celery": {
                "format": "[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s",
                "datefmt": "%Y/%m/%d %H:%M:%S",
            },
        },
        "filters": {"request_id": {"()": "log_request_id.filters.RequestIDFilter"}},
        "handlers": {
            "console": {
                "filters": [
                    "request_id",
                ],
                "class": "rich.logging.RichHandler",
                "formatter": "standard",
                "level": "DEBUG",
            },
            "error_file": {
                "filters": [
                    "request_id",
                ],
                "class": "logging.FileHandler",
                "formatter": "standard",
                "level": "DEBUG",
                "filename": ERROR_LOG_FILE_PATH,
            },
            "celery": {
                "level": CELERY_LOG_LEVEL,
                "class": "logging.FileHandler",
                "filename": CELERY_LOG_PATH,
                "formatter": "celery",
            },
        },
        "loggers": {
            "django": {
                "handlers": ["console"],
                "level": "INFO",
            },
            "django.db.backends": {
                "level": "DEBUG",
                "handlers": ["console"],
                "propagate": False,
            },
            "error": {
                "level": "DEBUG",
                "handlers": ["error_file"],
                "propagate": True,
            },
            "celery": {
                "handlers": ["celery"],
                "level": CELERY_LOG_LEVEL,
                "propagate": True,
            },
        },
    }
