# Generated by Django 5.2.5 on 2025-10-20 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='photo',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='photo',
            name='pub_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.CreateModel(
            name='PhotoHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_image', models.ImageField(upload_to='photo_updates')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models_app.photo')),
            ],
        ),
    ]
